config_version: 2
settings:
  bindings.commands:
    global:
      normal:
        J: tab-prev
        K: tab-next
  content.blocking.method:
    global: both
  content.headers.user_agent:
    https://accounts.google.com/*: Mozilla/5.0 ({os_info}; rv:84.0) Gecko/20100101
      Firefox/84.0
  content.notifications.enabled:
    https://mail.google.com: true
    https://web.whatsapp.com: true
    https://www.reddit.com: false
  content.register_protocol_handler:
    https://mail.google.com?extsrc=mailto&url=%25s: true
  downloads.location.directory:
    global: /home/triplek/DLDs
  downloads.location.prompt:
    global: false
  downloads.remove_finished:
    global: 0
  fileselect.handler:
    global: external
  fileselect.multiple_files.command:
    global:
    - st
    - -e
    - ranger
    - --choosefiles={}
  fileselect.single_file.command:
    global:
    - st
    - -e
    - ranger
    - --choosefile={}
  fonts.default_family:
    global: JetBrainsMono Nerd Font
  zoom.default:
    global: 125%
